### PR TITLE
feat(keyFilePath)!: fix misleading keyFilePath option

### LINKED ISSUE #3: callback from Apple fails
Hello, when I try to use your library on my nestjs code, on callback from Apple I have this error in my log:

`{"statusCode":500,"error":"error:1E08010C:DECODER routines::unsupported","timestamp":"2023-03-23T08:46:41.316Z","message":"Internal server error"}`

My server is nodejs 18, nestjs 9 and is deployed on Google Appengine Standard

Please, any clue?

### PR DESCRIPTION
**Pull request by kdelmonte**
**BREAKING CHANGE (bumped major version)**

The `keyFilePath` does not really expect a file path but the actual file contents. This is a bit confusing and some users have run into it already.

Also, updated README to provide a working example for users.

Fixes #3 and #4.

### CODE REVIEW

**Comment by kdelmonte** [comment]
@arendajaelu , hello! When do you think this could be published to nom?

**Comment by arendajaelu** [comment]
@kdelmonte Hey Bro, thank you for your contribution, I just published it on npm.js. Could you please check and test it? Much appreciate it.

**Comment by kdelmonte** [comment]
My pleasure. Thank you for this package! It is a real time saver. Unfortunately, I made a small mistake which I am fixing here: #6.

**Comment by arendajaelu** [comment]
Thank you for solving that quickly, :) Publishing to npm

**Pull request merged**
